### PR TITLE
retry body_as_text 3 times

### LINKED ISSUE #52: Spurious failure
https://github.com/dlang/dmd/runs/5326707082

Raw log:

```
2022-02-24T23:30:07.7453082Z Requested labels: macOS-10.15
2022-02-24T23:30:07.7453144Z Job defined at: dlang/dmd/.github/workflows/runnable_cxx.yml@refs/pull/13589/merge
2022-02-24T23:30:07.7453169Z Waiting for a runner to pick up this job...
2022-02-24T23:30:09.3241883Z Job is waiting for a hosted runner to come online.
2022-02-24T23:30:16.6545494Z Job is about to start running on the hosted runner: GitHub Actions 4 (hosted)
2022-02-24T23:30:20.5635840Z Current runner version: '2.287.1'
2022-02-24T23:30:20.5670850Z ##[group]Operating System
2022-02-24T23:30:20.5671450Z Mac OS X
2022-02-24T23:30:20.5671690Z 10.15.7
2022-02-24T23:30:20.5671910Z 19H1715
2022-02-24T23:30:20.5672150Z ##[endgroup]
2022-02-24T23:30:20.5672430Z ##[group]Virtual Environment
2022-02-24T23:30:20.5672750Z Environment: macos-10.15
2022-02-24T23:30:20.5673010Z Version: 20220219.1
2022-02-24T23:30:20.5673450Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20220219.1/images/macos/macos-10.15-Readme.md
2022-02-24T23:30:20.5674010Z Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20220219.1
2022-02-24T23:30:20.5674400Z ##[endgroup]
2022-02-24T23:30:20.5674690Z ##[group]Virtual Environment Provisioner
2022-02-24T23:30:20.5674990Z 1.0.0.0-main-20220215-1
2022-02-24T23:30:20.5675250Z ##[endgroup]
2022-02-24T23:30:20.5676110Z ##[group]GITHUB_TOKEN Permissions
2022-02-24T23:30:20.5676880Z Actions: read
2022-02-24T23:30:20.5677160Z Checks: read
2022-02-24T23:30:20.5677420Z Contents: read
2022-02-24T23:30:20.5677670Z Deployments: read
2022-02-24T23:30:20.5677940Z Discussions: read
2022-02-24T23:30:20.5678190Z Issues: read
2022-02-24T23:30:20.5678710Z Metadata: read
2022-02-24T23:30:20.5678970Z Packages: read
2022-02-24T23:30:20.5679220Z Pages: read
2022-02-24T23:30:20.5679480Z PullRequests: read
2022-02-24T23:30:20.5679760Z RepositoryProjects: read
2022-02-24T23:30:20.5680050Z SecurityEvents: read
2022-02-24T23:30:20.5680310Z Statuses: read
2022-02-24T23:30:20.5680580Z ##[endgroup]
2022-02-24T23:30:20.5685700Z Secret source: None
2022-02-24T23:30:20.5686130Z Prepare workflow directory
2022-02-24T23:30:20.6781850Z Prepare all required actions
2022-02-24T23:30:20.7065810Z Getting action download info
2022-02-24T23:30:20.9612890Z Download action repository 'dlang-community/setup-dlang@v1' (SHA:763d869b4d67e50c3ccd142108c8bca2da9df166)
2022-02-24T23:30:22.1898560Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
2022-02-24T23:30:22.9919600Z Download action repository 'actions/cache@v1' (SHA:70655ec8323daeeaa7ef06d7c56e1b9191396cbe)
2022-02-24T23:30:23.5406260Z Download action repository 'actions/upload-artifact@v2' (SHA:82c141cc518b40d92cc801eee768e7aafc9c2fa2)
2022-02-24T23:30:24.6571240Z ##[group]Run dlang-community/setup-dlang@v1
2022-02-24T23:30:24.6571590Z with:
2022-02-24T23:30:24.6571810Z   compiler: dmd-latest
2022-02-24T23:30:24.6572250Z   gh_token: ***
2022-02-24T23:30:24.6572490Z ##[endgroup]
2022-02-24T23:30:28.8800550Z Error: unrecognized DMD version: 
2022-02-24T23:30:28.8801520Z     at dmd (/Users/runner/work/_actions/dlang-community/setup-dlang/v1/dist/index.js:1:127324)
2022-02-24T23:30:28.8802000Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-02-24T23:30:28.8802680Z     at async Object.compiler (/Users/runner/work/_actions/dlang-community/setup-dlang/v1/dist/index.js:1:126504)
2022-02-24T23:30:28.8803310Z     at async run (/Users/runner/work/_actions/dlang-community/setup-dlang/v1/dist/index.js:1:133006)
2022-02-24T23:30:28.8864180Z ##[error]unrecognized DMD version: 
2022-02-24T23:30:28.9283000Z Cleaning up orphan processes
```

### PR DESCRIPTION
**Pull request by WebFreak001**
This should hopefully fix #52

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -1,8 +1,20 @@
...
 import { BearerCredentialHandler } from 'typed-rest-client/Handlers';
+import { IHttpClientResponse } from 'typed-rest-client/Interfaces';
 
 export async function body_as_text(url: string, token: string = ''): Promise<string> {
-    const bearer = token ? [ new BearerCredentialHandler(token) ] : undefined;
-    let client = new httpm.HttpClient("dlang-community/setup-dlang", bearer);
-    return (await (await client.get(url)).readBody()).trim();
+    let retry = 0;
+    let res: IHttpClientResponse | undefined = undefined;
+    for (; retry < 3; retry++) {
```
Comment (mihails-strasuns) [inline src/utils.ts:8]: Seems like there is a builtin retry interface https://github.com/microsoft/typed-rest-client/blob/f21ab8a105826b64bf5c2df81e1f341537d273c0/test/units/httptests.ts#L427 - can that be used?

**Comment by WebFreak001** [comment]
went with custom code after all, as sometimes right now we are rate-limted by 403, which is not retried by the built-in retry mechanism. Our mechanism also allows us finer control of the retry timeouts.
